apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: myapp-gitlab
  description: Demo of Django REST Framework JSON-API
  tags:
    - rest
spec:
  type: openapi
  lifecycle: development
  owner: vishal:guest
  definition:
    $openapi: https://api.apis.guru/v2/openapi.yaml
